### ISSUE TITLE
Texts/labels are always aligned left

### ISSUE THREAD

**Issue by germanocaumo** [bigbluebutton/bbb-presentation-video#24]
Texts/labels are not respecting the Alignment property anymore, they are always aligned on the left

From what I saw this was introduced with the show_layout_by_lines:
https://github.com/bigbluebutton/bbb-presentation-video/blob/main/bbb_presentation_video/renderer/tldraw/shape/text.py#L95

**Comment by kepstin** [comment]
Looks like when not using the full Pango.Layout, I'm responsible for horizontal positioning of each line.

The `show_layout_by_lines` method will need to:
* Get the full layout width
* Get the width of each individual line
* If necessary, flip the left/right alignment based on the line's [resolved_dir](https://docs.gtk.org/Pango/struct.LayoutLine.html) - reference the Pango internal [`get_alignment` function](https://gitlab.gnome.org/GNOME/pango/-/blob/818b549bafbaef9323ceedffb3930113ae008af7/pango/pango-layout.c#L2775)
* Calculate the x offset for the line based on line width, layout width, and alignment - reference the Pango internal [`get_x_offset` function](https://gitlab.gnome.org/GNOME/pango/-/blob/818b549bafbaef9323ceedffb3930113ae008af7/pango/pango-layout.c#L2794)
