### ISSUE TITLE
Why video player is needed to play video and public chat entries?

### ISSUE THREAD

**Issue by jpmirandaa** [bigbluebutton/bbb-presentation-video#41]
Hi all.
Recently I installed bbb-playback-video and cannot obtain an only mp4 file. The video link opens a page with a player which plays back video from webcams and screenshare but not the whiteboard or pdf presentation uploaded nor public chat entries.
The public chat entries are only able to view them with the visor webpage.
Is there any way to obtain just a mp4 file with webcams, audio, whiteboard with annotations or presentation uploaded, and public chat entries?
As reference, something like Daniel Petri's project did on BBB 2.3 to 2.5 versions.
(https://github.com/danielpetri1/bbb-recording-exporter)
Thanks in advance.
JP

**Comment by ffdixon** [comment]
Hi JP,

> The video link opens a page with a player which plays back video from webcams and screenshare but not the whiteboard or pdf presentation uploaded nor public chat entries.

Something isn't right in your setup.  You should see whiteboard + annotations, but not chat (we don't put the chat into the video, though if you checkout the code, you can extend it to support that too).

Can you confirm that you are playing the 'video' format?  What version of BigBlueButton are you running (this is a standard question we ask anyone who posts an issue)?  See
  
  https://docs.bigbluebutton.org./support/getting-help#help-installing-or-running-bigbluebutton

**Comment by kepstin** [comment]
The current BigBlueButton video format doesn't include the ability to include chat in the video. This is something that we'd like to add in a later BigBlueButton version.
