### ISSUE TITLE
Implement BBB 3.0 chat features

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bbb-presentation-video#57]
Adapt to https://github.com/bigbluebutton/bigbluebutton/pull/21713
similarly to https://github.com/bigbluebutton/bbb-playback/pull/286

**Comment by kepstin** [comment]
This is the incorrect place to file this issue - this tool only deals with generation of the video for the presentation area.

The changes need to be made in the recording processing scripts and playback files located in the BigBlueButton repo under `record-and-playback/core/lib` and `record-and-playback/video`
